export enum ERROR_CODE {
  WRONG_TURN = 'WRONG_TURN',
  FOLD_NOT_ALLOWED = 'FOLD_NOT_ALLOWED',
  CHECK_NOT_ALLOWED = 'CHECK_NOT_ALLOWED',
  CALL_NOT_ALLOWED = 'CALL_NOT_ALLOWED',
  RAISE_NOT_ALLOWED = 'RAISE_NOT_ALLOWED',
  RAISE_AMOUNT_TOO_SMALL = 'RAISE_AMOUNT_TOO_SMALL',
  RAISE_AMOUNT_TOO_BIG = 'RAISE_AMOUNT_TOO_BIG',
  ALL_IN_NOT_ALLOWED = 'ALL_IN_NOT_ALLOWED',
}
